language: android
env:
    global:
        - NDK_VERSION=r15c
        - NDK_CCACHE=ccache
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - PATH=${ANDROID_NDK_HOME}:${PATH}
android:
  components:
   - tools
   - platform-tools
   - tools
   - build-tools-26.0.2
   - build-tools-25.0.3
   - android-26
   - android-25
   - extra-android-m2repository
   - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
 - echo y | sdkmanager "tools"
 - echo y | sdkmanager "platform-tools"
 - echo y | sdkmanager "build-tools;25.0.3"
 - echo y | sdkmanager "build-tools;26.0.2"
 - echo y | sdkmanager "platforms;android-25"
 - echo y | sdkmanager "platforms;android-26"
 - echo y | sdkmanager "extras;android;m2repository"
 - echo y | sdkmanager "extras;google;m2repository"
 - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.0-alpha7"
 - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.0-alpha7"
  
install:
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          pushd $HOME/.android;
          export ARCH=`uname -m`;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          popd;
      fi
script:
     - ./gradlew assembleRelease
before_deploy:
     - cp ./app/build/outputs/apk/*.apk
deploy:
  provider: releases
  api_key: 
    secure: "Ep9lbrfDoZYfjEkIL5etZWOPcvz1b1fqO/8ECZarYPGNtjsDRRMs8C8c756pvddsjv2KDbFhHVS6U+YSvkqd6J/hkWDJiUNU4f6qcncJ7AT6SZ80ZgaNtvB5PP9FKvNQeIJp78zvhf61h0DttI+sf/+xX6SvyNQCblOOmsxf4Td1o9fo6Upm/Fv3VK9EhllzVPfndTX+ulUNXFQ+3FBEaQb/ITrhZvIPL09hHBACBA7+HTpc9BReFs6RCeIk1BWQWr3h6PPD1dnz95HnIYrVVScDTimwAdbl2Iih7RutLJ8NA0x7fVbeeeU9g1ocpGkOaI0KZct7JTSF5COo5ou1I/O24gMc2lgAhYtFJQRf26YZyCjD2woU6+83qQBhdKxlvulcQlI8JYqfG97cJt5yfIlT9gDkLD6hX+XBFsqJAwV/AxXk1wM2ZieVWO64ZjfB3ghDYoXx+jUFDl4xpcn73PYTFzrbi2If0TSLjqfzzbYWLq0F/FrGqr5cm8/kQjSNHUoKnv7y9DTKpZDaYJqWGtctg8N1qj7DEutX09uyGyR3ef90sza7P5Djtmw69HMKSeFZMXB2zKZtC4jp2I/uiqvH7YlVRrEaN0s/j+7K2ULuEOdLlXMZGWV16hw3jdqKktMXCk37bU9dICPrsWKJns//wFXjMDIwEfjqjiNUQhI="
  file: 
    - "app-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
